[package]
name = "raytracer-obj"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
log.workspace = true
raytracer-impl = { path = "../raytracer-impl" }
thiserror = "1.0"
image = "0.24.7"
