[package]
name = "raytracer-samples"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rand.workspace = true
raytracer-impl = { path = "../raytracer-impl" }
raytracer-obj = { path = "../raytracer-obj" }
rand_xorshift = "0.4"
